site_name: whoiam Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Configuration: configuration.md
  - Contributing: contributing.md
  - License: license.md
